# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- xplor-build

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: make tag-latest
  displayName: 'Build and Tag'

- task: Docker@2
  inputs:
    containerRegistry: 'xplorfin'
    command: 'login'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: make push-latest
  displayName: "Docker Push"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
